# -------------------------------------------------------
# TECHNOGIX
# -------------------------------------------------------
# Copyright (c) [2022] Technogix SARL
# All rights reserved
# -------------------------------------------------------
# Pull request pipeline for container
# -------------------------------------------------------
# Nadège LEMPERIERE, @01 march 2022
# Latest revision: 01 march 2022
# -------------------------------------------------------

name: Container Pull Request Pipeline

on:
    pull_request:
        types: [ assigned, opened, synchronize, reopened ]

jobs:

    check:
        name: Check Container
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Check dockerfile
              uses: hadolint/hadolint-action@v1.6.0
              with:
                dockerfile: Dockerfile
                failure-threshold: ignore

    build:
        name: Build Container
        runs-on: ubuntu-latest
        needs: [check]
        env:
            dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
            dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Build container
              run: docker image build -t technogix/${{ github.event.repository.name }}:${{ github.sha }} .

            - name: Check container
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: 'technogix/${{ github.event.repository.name }}:${{ github.sha }}'
                format: 'sarif'
                output: trivy.sarif
                exit-code: '0'
                ignore-unfixed: true


            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/docker@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                image: 'technogix/${{ github.event.repository.name }}:${{ github.sha }}'
                args: --sarif-file-output=snyk.sarif --file=Dockerfile

            - name: Upload trivy result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                sarif_file: trivy.sarif

            - name: Upload snyk result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                sarif_file: snyk.sarif

            - name: Login to dockerhub registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

            - name: Publish container
              run: docker image push technogix/${{ github.event.repository.name }}:${{ github.sha }}
