# -------------------------------------------------------
# Copyright (c) [2022] Nadege Lemperiere
# All rights reserved
# -------------------------------------------------------
# Security analysis pipeline for terraform container
# -------------------------------------------------------
# Nadège LEMPERIERE, @01 march 2022
# Latest revision: 19 november 2023
# -------------------------------------------------------

name: Container Security Regular Scan Pipeline

on:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
    analyze:
        name: Analyze Container
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Build container
              run: docker image build -t ${{ github.repository }}:${{ github.sha }} .

            - name: Check container
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: '${{ github.repository }}:${{ github.sha }}'
                format: 'sarif'
                output: trivy.sarif
                exit-code: '0'
                ignore-unfixed: true

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/docker@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                image: '${{ github.repository }}:${{ github.sha }}'
                args: --sarif-file-output=snyk.sarif --file=Dockerfile

            - name: Upload trivy result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@main
              if: always()
              with:
                sarif_file: trivy.sarif

            - name: Upload snyk result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@main
              if: always()
              with:
                sarif_file: snyk.sarif